language: python
dist: trusty
python:
  - "2.7"
install:
  - pip install flake8
  - npm install -g eslint stylelint
script:
  - flake8 .
  - eslint 'db/static/js/*.js'
  - stylelint 'db/static/css/*.css'
